apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  type: ClusterIP
  selector:
    app: my-react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
