apiVersion: v1
kind: Service
metadata:
        name: webscraper
spec:
        ports:
                - port: 5000
                  protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
        name: mysqldb
spec:
        ports:
                - port: 3306
                  protocol: TCP
        selector:
                app: mysqldb
apiVersion: v1
kind: Service
metadata:
        name: chatbot
spec:
        ports:
                - name: rasa
                  protocol: TCP
                  port: 5005
                - name: actions
                  protocol: TCP
                  port: 5055
